import Head from "next/head";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import Career from "../../components/Career";

export default function Client() {
  return (
    <div>
      <Head>
        <title>Career - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <Career />
      <Footer />
    </div>
  );
}
