import Head from "next/head";
import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";
import Portofolio from "../../../components/Portofolio";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Detail Services - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <Portofolio />
      <Footer />
    </div>
  );
}
