import Head from "next/head";
import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";
import Portofolio from "../../../components/Portofolio";
import { rootUrl } from "../../../constants";

export async function getStaticPaths() {
  return {
    paths: [{ params: { detail: "4100" } }],
    fallback: "blocking",
  };
}

export async function getStaticProps({ params: { detail } }) {
  const slidesRes = await (
    await fetch(rootUrl + "/slides?_embed&_fields=acm_fields")
  ).json();

  const slides = slidesRes.map(({ acm_fields: { title, text, image } }) => ({
    title,
    text,
    image: image.source_url,
  }));

  return {
    props: {
      slides,
    },
    revalidate: 5 * 60 * 1000,
  };
}

export default function Home({ slides }) {
  return (
    <div>
      <Head>
        <title>Detail Services - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <Portofolio sliderImage={slides} />
      <Footer />
    </div>
  );
}
