import Head from "next/head";
import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";
import ArchitectureConstructionManagement from "../../../components/ArchitectureConstructionManagement";
import { request, gql } from "graphql-request";

export async function getStaticProps() {
  const query = gql`
    {
      items: architecturePages(first: 1) {
        nodes {
          ...ArchitecturePageFields
        }
      }
    }

    fragment ArchitecturePageFields on ArchitecturePage {
      title
      description
      subserviceTitle
      subserviceDescription
      subserviceProjects {
        mediaItemId
        mediaItemUrl
        altText
        caption
        description
        title
      }
    }
  `;

  const { items } = await request(
    "https://www.handalselaras.com/graphql/",
    query
  );

  return {
    props: {
      data: items.nodes[0],
    },
    revalidate: 1 * 30,
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Architecture & Construction - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <ArchitectureConstructionManagement pageData={data} />
      <Footer />
    </div>
  );
}
