import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AboutUs from "../components/AboutUs";
import { useState } from "react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>About Us - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <AboutUs />
      <Footer />
    </div>
  );
}
