import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Clients from "../components/Clients";

export default function Client() {
  return (
    <div>
      <Head>
        <title>Clients - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <Clients />
      <Footer />
    </div>
  );
}
