import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Gallery from "../components/Gallery";

export default function Client() {
  return (
    <div>
      <Head>
        <title>Gallery - KHS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Navbar />
      <Gallery />
      <Footer />
    </div>
  );
}
