import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HomePage from "../components/HomePage";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - KHS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Navbar />
      <HomePage />
      <Footer />
    </div>
  );
}
