import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HomePage from "../components/HomePage";
import { request, gql } from "graphql-request";

export async function getStaticProps() {
  const query = gql`
    {
      items: homePages(first: 1) {
        nodes {
          ...HomePageFields
        }
      }
    }

    fragment HomePageFields on HomePage {
      section1 {
        mediaItemId
        mediaItemUrl
        title
        altText
        caption
        description
      }
      section2Title
      section2Description
      section2Image {
        mediaItemId
        mediaItemUrl
        altText
        caption
        description
      }
      section3Title
      section3Description
      section4Title
      section4Description
      section5Title
      section5Description
      section6Text
    }
  `;

  const { items } = await request(
    "https://www.handalselaras.com/graphql/",
    query
  );

  return {
    props: {
      data: items.nodes[0],
    },
    revalidate: 5 * 60 * 1000,
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Home - KHS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>
      <Navbar />
      <HomePage pageData={data} />
      <Footer />
    </div>
  );
}
